M48
; DRILL file {KiCad 7.0.6-71-g49772d2539} date Mon Aug  7 20:47:20 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-07T20:47:20-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-71-g49772d2539
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X78.047Y-94.14
X78.047Y-99.92
T0
M30
